
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-azure
  template:
    metadata:
      labels:
        app: spring-boot-azure
    spec:
      containers:
      - name: my-spring-boot-azure
        image: azurecontainer99.azurecr.io/joaof-design/spring-boot-azure:34
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-boot-azure
    k8s-app: spring-boot-azure
  name: spring-boot-azure
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: spring-boot-azure
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-boot-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
        - path: /expose
          backend:
          service:
            name: spring-boot-azure
            port:
              number: 8085
